branch: main
commit_message: 'feat: initial commit'
committer_email: hbraswel@redhat.com
committer_name: hbraswelrh
markdown_dir: markdown/
#repo_path: /home/hbraswel/GIT/trestle-workspace
repo_path: .
