name: Autosync

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'

jobs:
  autosync:
    name: Autosync JSON and Markdown data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run autosync
        id: autosync
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@main
        with:
          markdown_dir: "markdown/profiles"
          oscal_model: "profile"
          branch: "main"
          file_patterns: "*.json,markdown/*"
