name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congrats! This is your first issue in the trestle-workspace:tada"
        pr-message: "Congrats! You have now opened your first Pull Request in the trestle-workspace :tada"
